name: vlm
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - argon2-cffi-bindings=21.2.0
  - async-lru=2.0.4
  - attrs=24.3.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.3
  - bleach=6.2.0
  - brotli-python=1.0.9
  - ca-certificates=2025.2.25
  - cffi=1.17.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - h11=0.14.0
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - ipykernel=6.29.5
  - jedi=0.19.2
  - jinja2=3.1.5
  - jsonschema=4.23.0
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.27.3
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc=7.2.0
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - markupsafe=3.0.2
  - nbconvert-core=7.16.5
  - nbconvert-pandoc=7.16.5
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - notebook=7.3.2
  - openssl=3.0.15
  - packaging=24.2
  - pandoc=2.12
  - parso=0.8.4
  - pickleshare=0.7.5
  - pip=24.2
  - prometheus_client=0.21.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pysocks=1.7.1
  - python=3.9.21
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=3.2.1
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.22.3
  - setuptools=75.1.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tinycss2=1.4.0
  - tk=8.6.14
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - urllib3=2.3.0
  - websocket-client=1.8.0
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - accelerate==1.3.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.8.0
      - argon2-cffi==23.1.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - babel==2.17.0
      - certifi==2024.12.14
      - charset-normalizer==3.4.1
      - click==8.1.8
      - clip==0.2.0
      - cma==4.0.0
      - comm==0.2.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - datasets==3.2.0
      - datum==1.13.0
      - debugpy==1.8.12
      - deepspeed==0.16.2
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - einops==0.8.0
      - entrypoints==0.3
      - eval-type-backport==0.2.2
      - evaluate==0.4.3
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.16.1
      - flake8==3.7.9
      - flatbuffers==25.2.10
      - fonttools==4.55.4
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - ftfy==6.3.1
      - future==1.0.0
      - gast==0.6.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-pasta==0.2.0
      - grpcio==1.69.0
      - h5py==3.12.1
      - hjson==3.1.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.27.1
      - idna==3.10
      - importlib-resources==6.5.2
      - ipython==8.12.3
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - isort==4.3.21
      - joblib==1.4.2
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-widgets==3.0.13
      - kaggle==1.6.17
      - keras==3.10.0
      - kiwisolver==1.4.7
      - libclang==18.1.1
      - littleutils==0.2.4
      - markdown==3.7
      - markdown-it-py==3.0.0
      - matplotlib==3.9.4
      - matplotlib-inline==0.1.7
      - mccabe==0.6.1
      - mdurl==0.1.2
      - mistune==3.1.1
      - ml-dtypes==0.5.1
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - namex==0.1.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - networkx==3.2.1
      - ninja==1.11.1.3
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-ml-py==12.560.30
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - ogb==1.3.6
      - open-clip-torch==2.32.0
      - opt-einsum==3.4.0
      - optree==0.17.0
      - outdated==0.2.2
      - overrides==7.7.0
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - peft==0.14.0
      - pexpect==4.9.0
      - pillow==11.1.0
      - pipreqs==0.5.0
      - platformdirs==4.3.6
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - propcache==0.2.1
      - protobuf==5.29.2
      - psutil==6.1.1
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==19.0.0
      - pycodestyle==2.5.0
      - pycparser==2.22
      - pydantic==2.10.5
      - pydantic-core==2.27.2
      - pyflakes==2.1.1
      - pygments==2.19.1
      - pyparsing==3.2.1
      - python-slugify==8.0.4
      - pytz==2024.2
      - pyzmq==26.2.1
      - referencing==0.36.2
      - regex==2024.11.6
      - rich==14.1.0
      - safetensors==0.5.2
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - send2trash==1.8.3
      - sentry-sdk==2.20.0
      - setproctitle==1.3.4
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tb-nightly==2.19.0a20250108
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.1.0
      - terminado==0.18.1
      - text-unidecode==1.3
      - threadpoolctl==3.5.0
      - timm==1.0.15
      - tokenizers==0.21.0
      - tomli==2.2.1
      - torch==2.5.1
      - torchaudio==2.5.1
      - torchinfo==1.8.0
      - torchvision==0.20.1
      - tqdm==4.67.1
      - transformers==4.47.1
      - triton==3.1.0
      - types-python-dateutil==2.9.0.20241206
      - tzdata==2024.2
      - ujson==5.10.0
      - uri-template==1.3.0
      - wandb==0.19.5
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.13
      - wilds==1.2.2
      - wrapt==1.17.2
      - xxhash==3.5.0
      - yacs==0.1.8
      - yapf==0.29.0
      - yarg==0.1.9
      - yarl==1.18.3
prefix: /home/yifanyang/miniconda3/envs/vlm
